a = float(input())
b = float(input())
c = float(input())
d = float(input())
e = float(input())
f = float(input())
result = 0
if a >= 0:
    result += 1
if b >= 0:
    result += 1
if c >= 0:
    result += 1
if d >= 0:
    result += 1
if e >= 0:
    result += 1
if f >= 0:
    result += 1
print('{} valores positivos'.format(result))